# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MonkeyTestUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(648, 540)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 60, 801, 541))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_devices = QtWidgets.QWidget()
        self.tab_devices.setObjectName("tab_devices")
        self.label_2 = QtWidgets.QLabel(self.tab_devices)
        self.label_2.setGeometry(QtCore.QRect(40, 12, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_device1 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device1.setGeometry(QtCore.QRect(110, 17, 151, 20))
        self.lineEdit_device1.setObjectName("lineEdit_device1")
        self.checkBox_device1 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device1.setGeometry(QtCore.QRect(270, 20, 16, 16))
        self.checkBox_device1.setText("")
        self.checkBox_device1.setObjectName("checkBox_device1")
        self.label_3 = QtWidgets.QLabel(self.tab_devices)
        self.label_3.setGeometry(QtCore.QRect(40, 82, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.checkBox_device2 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device2.setGeometry(QtCore.QRect(270, 90, 16, 16))
        self.checkBox_device2.setText("")
        self.checkBox_device2.setObjectName("checkBox_device2")
        self.lineEdit_device2 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device2.setGeometry(QtCore.QRect(110, 87, 151, 20))
        self.lineEdit_device2.setObjectName("lineEdit_device2")
        self.lineEdit_device3 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device3.setGeometry(QtCore.QRect(110, 157, 151, 20))
        self.lineEdit_device3.setObjectName("lineEdit_device3")
        self.label_4 = QtWidgets.QLabel(self.tab_devices)
        self.label_4.setGeometry(QtCore.QRect(40, 152, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.checkBox_device3 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device3.setGeometry(QtCore.QRect(270, 160, 16, 16))
        self.checkBox_device3.setText("")
        self.checkBox_device3.setObjectName("checkBox_device3")
        self.lineEdit_device4 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device4.setGeometry(QtCore.QRect(110, 227, 151, 20))
        self.lineEdit_device4.setObjectName("lineEdit_device4")
        self.label_5 = QtWidgets.QLabel(self.tab_devices)
        self.label_5.setGeometry(QtCore.QRect(40, 222, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.checkBox_device4 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device4.setGeometry(QtCore.QRect(270, 230, 16, 16))
        self.checkBox_device4.setText("")
        self.checkBox_device4.setObjectName("checkBox_device4")
        self.lineEdit_device5 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device5.setGeometry(QtCore.QRect(110, 297, 151, 20))
        self.lineEdit_device5.setObjectName("lineEdit_device5")
        self.label_6 = QtWidgets.QLabel(self.tab_devices)
        self.label_6.setGeometry(QtCore.QRect(40, 292, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.checkBox_device5 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device5.setGeometry(QtCore.QRect(270, 300, 16, 16))
        self.checkBox_device5.setText("")
        self.checkBox_device5.setObjectName("checkBox_device5")
        self.lineEdit_device6 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device6.setGeometry(QtCore.QRect(420, 17, 151, 20))
        self.lineEdit_device6.setObjectName("lineEdit_device6")
        self.label_7 = QtWidgets.QLabel(self.tab_devices)
        self.label_7.setGeometry(QtCore.QRect(350, 12, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.checkBox_device6 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device6.setGeometry(QtCore.QRect(580, 20, 16, 16))
        self.checkBox_device6.setText("")
        self.checkBox_device6.setObjectName("checkBox_device6")
        self.lineEdit_device7 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device7.setGeometry(QtCore.QRect(420, 87, 151, 20))
        self.lineEdit_device7.setObjectName("lineEdit_device7")
        self.label_8 = QtWidgets.QLabel(self.tab_devices)
        self.label_8.setGeometry(QtCore.QRect(350, 82, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.checkBox_device7 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device7.setGeometry(QtCore.QRect(580, 90, 16, 16))
        self.checkBox_device7.setText("")
        self.checkBox_device7.setObjectName("checkBox_device7")
        self.lineEdit_device8 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device8.setGeometry(QtCore.QRect(420, 157, 151, 20))
        self.lineEdit_device8.setObjectName("lineEdit_device8")
        self.label_9 = QtWidgets.QLabel(self.tab_devices)
        self.label_9.setGeometry(QtCore.QRect(350, 152, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.checkBox_device8 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device8.setGeometry(QtCore.QRect(580, 160, 16, 16))
        self.checkBox_device8.setText("")
        self.checkBox_device8.setObjectName("checkBox_device8")
        self.lineEdit_device9 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device9.setGeometry(QtCore.QRect(420, 227, 151, 20))
        self.lineEdit_device9.setObjectName("lineEdit_device9")
        self.label_10 = QtWidgets.QLabel(self.tab_devices)
        self.label_10.setGeometry(QtCore.QRect(350, 222, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.checkBox_device9 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device9.setGeometry(QtCore.QRect(580, 230, 16, 16))
        self.checkBox_device9.setText("")
        self.checkBox_device9.setObjectName("checkBox_device9")
        self.lineEdit_device10 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device10.setGeometry(QtCore.QRect(420, 297, 151, 20))
        self.lineEdit_device10.setObjectName("lineEdit_device10")
        self.label_11 = QtWidgets.QLabel(self.tab_devices)
        self.label_11.setGeometry(QtCore.QRect(340, 292, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.checkBox_device10 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device10.setGeometry(QtCore.QRect(580, 300, 16, 16))
        self.checkBox_device10.setText("")
        self.checkBox_device10.setObjectName("checkBox_device10")
        self.pushButton_getDevicesID = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_getDevicesID.setGeometry(QtCore.QRect(50, 370, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_getDevicesID.setFont(font)
        self.pushButton_getDevicesID.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_getDevicesID.setObjectName("pushButton_getDevicesID")
        self.pushButton_getDevicesID_2 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_getDevicesID_2.setGeometry(QtCore.QRect(360, 370, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_getDevicesID_2.setFont(font)
        self.pushButton_getDevicesID_2.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_getDevicesID_2.setObjectName("pushButton_getDevicesID_2")
        self.pushButton_stop1 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop1.setGeometry(QtCore.QRect(110, 50, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop1.setFont(font)
        self.pushButton_stop1.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop1.setObjectName("pushButton_stop1")
        self.pushButton_stop2 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop2.setGeometry(QtCore.QRect(110, 120, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop2.setFont(font)
        self.pushButton_stop2.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop2.setObjectName("pushButton_stop2")
        self.pushButton_stop3 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop3.setGeometry(QtCore.QRect(110, 190, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop3.setFont(font)
        self.pushButton_stop3.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop3.setObjectName("pushButton_stop3")
        self.pushButton_stop4 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop4.setGeometry(QtCore.QRect(110, 260, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop4.setFont(font)
        self.pushButton_stop4.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop4.setObjectName("pushButton_stop4")
        self.pushButton_stop5 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop5.setGeometry(QtCore.QRect(110, 330, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop5.setFont(font)
        self.pushButton_stop5.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop5.setObjectName("pushButton_stop5")
        self.pushButton_stop6 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop6.setGeometry(QtCore.QRect(420, 50, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop6.setFont(font)
        self.pushButton_stop6.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop6.setObjectName("pushButton_stop6")
        self.pushButton_stop7 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop7.setGeometry(QtCore.QRect(420, 120, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop7.setFont(font)
        self.pushButton_stop7.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop7.setObjectName("pushButton_stop7")
        self.pushButton_stop8 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop8.setGeometry(QtCore.QRect(420, 190, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop8.setFont(font)
        self.pushButton_stop8.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop8.setObjectName("pushButton_stop8")
        self.pushButton_stop9 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop9.setGeometry(QtCore.QRect(420, 260, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop9.setFont(font)
        self.pushButton_stop9.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop9.setObjectName("pushButton_stop9")
        self.pushButton_stop10 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop10.setGeometry(QtCore.QRect(420, 330, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop10.setFont(font)
        self.pushButton_stop10.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop10.setObjectName("pushButton_stop10")
        self.tabWidget.addTab(self.tab_devices, "")
        self.tab_all = QtWidgets.QWidget()
        self.tab_all.setObjectName("tab_all")
        self.checkBox_isCerStop_All = QtWidgets.QCheckBox(self.tab_all)
        self.checkBox_isCerStop_All.setGeometry(QtCore.QRect(40, 220, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_isCerStop_All.setFont(font)
        self.checkBox_isCerStop_All.setObjectName("checkBox_isCerStop_All")
        self.lineEdit_time_all = QtWidgets.QLineEdit(self.tab_all)
        self.lineEdit_time_all.setGeometry(QtCore.QRect(140, 50, 181, 25))
        self.lineEdit_time_all.setObjectName("lineEdit_time_all")
        self.label_times_all = QtWidgets.QLabel(self.tab_all)
        self.label_times_all.setGeometry(QtCore.QRect(40, 50, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_times_all.setFont(font)
        self.label_times_all.setObjectName("label_times_all")
        self.lineEdit_dely_all = QtWidgets.QLineEdit(self.tab_all)
        self.lineEdit_dely_all.setGeometry(QtCore.QRect(410, 50, 161, 25))
        self.lineEdit_dely_all.setObjectName("lineEdit_dely_all")
        self.label_dely_all = QtWidgets.QLabel(self.tab_all)
        self.label_dely_all.setGeometry(QtCore.QRect(360, 50, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_dely_all.setFont(font)
        self.label_dely_all.setObjectName("label_dely_all")
        self.checkBox_isRushStop_All = QtWidgets.QCheckBox(self.tab_all)
        self.checkBox_isRushStop_All.setGeometry(QtCore.QRect(40, 160, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_isRushStop_All.setFont(font)
        self.checkBox_isRushStop_All.setObjectName("checkBox_isRushStop_All")
        self.checkBox_isAnrStop_All = QtWidgets.QCheckBox(self.tab_all)
        self.checkBox_isAnrStop_All.setGeometry(QtCore.QRect(310, 160, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_isAnrStop_All.setFont(font)
        self.checkBox_isAnrStop_All.setObjectName("checkBox_isAnrStop_All")
        self.checkBox_isAppErrStop_All = QtWidgets.QCheckBox(self.tab_all)
        self.checkBox_isAppErrStop_All.setGeometry(QtCore.QRect(310, 220, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_isAppErrStop_All.setFont(font)
        self.checkBox_isAppErrStop_All.setObjectName("checkBox_isAppErrStop_All")
        self.pushButton_start_All = QtWidgets.QPushButton(self.tab_all)
        self.pushButton_start_All.setGeometry(QtCore.QRect(40, 330, 551, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_start_All.setFont(font)
        self.pushButton_start_All.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_start_All.setObjectName("pushButton_start_All")
        self.checkBox = QtWidgets.QCheckBox(self.tab_all)
        self.checkBox.setGeometry(QtCore.QRect(40, 110, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_kill_all = QtWidgets.QCheckBox(self.tab_all)
        self.checkBox_kill_all.setGeometry(QtCore.QRect(40, 280, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_kill_all.setFont(font)
        self.checkBox_kill_all.setObjectName("checkBox_kill_all")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_all)
        self.checkBox_2.setGeometry(QtCore.QRect(310, 110, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.tabWidget.addTab(self.tab_all, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.spinBox_seed = QtWidgets.QSpinBox(self.tab)
        self.spinBox_seed.setGeometry(QtCore.QRect(120, 40, 111, 30))
        self.spinBox_seed.setObjectName("spinBox_seed")
        self.label_seed = QtWidgets.QLabel(self.tab)
        self.label_seed.setGeometry(QtCore.QRect(60, 40, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_seed.setFont(font)
        self.label_seed.setObjectName("label_seed")
        self.spinBox_flip = QtWidgets.QSpinBox(self.tab)
        self.spinBox_flip.setGeometry(QtCore.QRect(430, 40, 111, 30))
        self.spinBox_flip.setObjectName("spinBox_flip")
        self.label_flip = QtWidgets.QLabel(self.tab)
        self.label_flip.setGeometry(QtCore.QRect(370, 40, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_flip.setFont(font)
        self.label_flip.setObjectName("label_flip")
        self.spinBox_touch = QtWidgets.QSpinBox(self.tab)
        self.spinBox_touch.setGeometry(QtCore.QRect(120, 100, 111, 30))
        self.spinBox_touch.setObjectName("spinBox_touch")
        self.label_touch = QtWidgets.QLabel(self.tab)
        self.label_touch.setGeometry(QtCore.QRect(50, 100, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_touch.setFont(font)
        self.label_touch.setObjectName("label_touch")
        self.spinBox_trackball = QtWidgets.QSpinBox(self.tab)
        self.spinBox_trackball.setGeometry(QtCore.QRect(120, 160, 111, 30))
        self.spinBox_trackball.setObjectName("spinBox_trackball")
        self.label_trackball = QtWidgets.QLabel(self.tab)
        self.label_trackball.setGeometry(QtCore.QRect(22, 160, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_trackball.setFont(font)
        self.label_trackball.setObjectName("label_trackball")
        self.spinBox_majornav = QtWidgets.QSpinBox(self.tab)
        self.spinBox_majornav.setGeometry(QtCore.QRect(120, 220, 111, 30))
        self.spinBox_majornav.setObjectName("spinBox_majornav")
        self.label_majornav = QtWidgets.QLabel(self.tab)
        self.label_majornav.setGeometry(QtCore.QRect(30, 220, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_majornav.setFont(font)
        self.label_majornav.setObjectName("label_majornav")
        self.spinBox_appswitch = QtWidgets.QSpinBox(self.tab)
        self.spinBox_appswitch.setGeometry(QtCore.QRect(120, 290, 111, 30))
        self.spinBox_appswitch.setObjectName("spinBox_appswitch")
        self.label_appswitch = QtWidgets.QLabel(self.tab)
        self.label_appswitch.setGeometry(QtCore.QRect(20, 290, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_appswitch.setFont(font)
        self.label_appswitch.setObjectName("label_appswitch")
        self.spinBox_motion = QtWidgets.QSpinBox(self.tab)
        self.spinBox_motion.setGeometry(QtCore.QRect(430, 100, 111, 30))
        self.spinBox_motion.setObjectName("spinBox_motion")
        self.label_motion = QtWidgets.QLabel(self.tab)
        self.label_motion.setGeometry(QtCore.QRect(355, 100, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_motion.setFont(font)
        self.label_motion.setObjectName("label_motion")
        self.spinBox_nav = QtWidgets.QSpinBox(self.tab)
        self.spinBox_nav.setGeometry(QtCore.QRect(430, 160, 111, 30))
        self.spinBox_nav.setObjectName("spinBox_nav")
        self.label_nav = QtWidgets.QLabel(self.tab)
        self.label_nav.setGeometry(QtCore.QRect(375, 160, 31, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_nav.setFont(font)
        self.label_nav.setObjectName("label_nav")
        self.spinBox_syskeys = QtWidgets.QSpinBox(self.tab)
        self.spinBox_syskeys.setGeometry(QtCore.QRect(430, 220, 111, 30))
        self.spinBox_syskeys.setObjectName("spinBox_syskeys")
        self.label_syskeys = QtWidgets.QLabel(self.tab)
        self.label_syskeys.setGeometry(QtCore.QRect(345, 220, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_syskeys.setFont(font)
        self.label_syskeys.setObjectName("label_syskeys")
        self.spinBox_anyevent = QtWidgets.QSpinBox(self.tab)
        self.spinBox_anyevent.setGeometry(QtCore.QRect(430, 290, 111, 30))
        self.spinBox_anyevent.setObjectName("spinBox_anyevent")
        self.label_anyevent = QtWidgets.QLabel(self.tab)
        self.label_anyevent.setGeometry(QtCore.QRect(335, 290, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_anyevent.setFont(font)
        self.label_anyevent.setObjectName("label_anyevent")
        self.pushButton_resetpar = QtWidgets.QPushButton(self.tab)
        self.pushButton_resetpar.setGeometry(QtCore.QRect(50, 360, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_resetpar.setFont(font)
        self.pushButton_resetpar.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_resetpar.setObjectName("pushButton_resetpar")
        self.pushButton_savepar = QtWidgets.QPushButton(self.tab)
        self.pushButton_savepar.setGeometry(QtCore.QRect(340, 360, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_savepar.setFont(font)
        self.pushButton_savepar.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_savepar.setObjectName("pushButton_savepar")
        self.tabWidget.addTab(self.tab, "")
        self.tab_black = QtWidgets.QWidget()
        self.tab_black.setObjectName("tab_black")
        self.pushButton_addbacklist = QtWidgets.QPushButton(self.tab_black)
        self.pushButton_addbacklist.setGeometry(QtCore.QRect(300, 170, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_addbacklist.setFont(font)
        self.pushButton_addbacklist.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_addbacklist.setObjectName("pushButton_addbacklist")
        self.pushButton_rmbacklist = QtWidgets.QPushButton(self.tab_black)
        self.pushButton_rmbacklist.setGeometry(QtCore.QRect(300, 260, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_rmbacklist.setFont(font)
        self.pushButton_rmbacklist.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_rmbacklist.setObjectName("pushButton_rmbacklist")
        self.listView_appbacklist = QtWidgets.QListView(self.tab_black)
        self.listView_appbacklist.setGeometry(QtCore.QRect(20, 10, 256, 361))
        self.listView_appbacklist.setObjectName("listView_appbacklist")
        self.listView_black = QtWidgets.QListView(self.tab_black)
        self.listView_black.setGeometry(QtCore.QRect(370, 10, 256, 361))
        self.listView_black.setObjectName("listView_black")
        self.pushButton_getPackNamebacklist = QtWidgets.QPushButton(self.tab_black)
        self.pushButton_getPackNamebacklist.setGeometry(QtCore.QRect(300, 80, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_getPackNamebacklist.setFont(font)
        self.pushButton_getPackNamebacklist.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_getPackNamebacklist.setObjectName("pushButton_getPackNamebacklist")
        self.pushButton_saveBlacklist = QtWidgets.QPushButton(self.tab_black)
        self.pushButton_saveBlacklist.setGeometry(QtCore.QRect(550, 380, 45, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_saveBlacklist.setFont(font)
        self.pushButton_saveBlacklist.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_saveBlacklist.setObjectName("pushButton_saveBlacklist")
        self.label_balcklistpath = QtWidgets.QLabel(self.tab_black)
        self.label_balcklistpath.setGeometry(QtCore.QRect(10, 380, 121, 30))
        self.label_balcklistpath.setObjectName("label_balcklistpath")
        self.lineEdit_black_list_path = QtWidgets.QLineEdit(self.tab_black)
        self.lineEdit_black_list_path.setEnabled(False)
        self.lineEdit_black_list_path.setGeometry(QtCore.QRect(137, 382, 401, 25))
        self.lineEdit_black_list_path.setObjectName("lineEdit_black_list_path")
        self.tabWidget.addTab(self.tab_black, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.listView_whitelistapp = QtWidgets.QListView(self.tab_2)
        self.listView_whitelistapp.setGeometry(QtCore.QRect(20, 10, 256, 361))
        self.listView_whitelistapp.setObjectName("listView_whitelistapp")
        self.listView_whitelist = QtWidgets.QListView(self.tab_2)
        self.listView_whitelist.setGeometry(QtCore.QRect(370, 10, 256, 361))
        self.listView_whitelist.setObjectName("listView_whitelist")
        self.pushButton_whitelistget = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_whitelistget.setGeometry(QtCore.QRect(300, 60, 40, 40))
        self.pushButton_whitelistget.setObjectName("pushButton_whitelistget")
        self.pushButton_whitelistadd = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_whitelistadd.setGeometry(QtCore.QRect(300, 150, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_whitelistadd.setFont(font)
        self.pushButton_whitelistadd.setObjectName("pushButton_whitelistadd")
        self.pushButton_whitelistrm = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_whitelistrm.setGeometry(QtCore.QRect(300, 240, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_whitelistrm.setFont(font)
        self.pushButton_whitelistrm.setObjectName("pushButton_whitelistrm")
        self.label_whitelistpath = QtWidgets.QLabel(self.tab_2)
        self.label_whitelistpath.setGeometry(QtCore.QRect(20, 380, 111, 21))
        self.label_whitelistpath.setObjectName("label_whitelistpath")
        self.lineEdit_whitelistpath = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_whitelistpath.setEnabled(False)
        self.lineEdit_whitelistpath.setGeometry(QtCore.QRect(140, 380, 411, 25))
        self.lineEdit_whitelistpath.setObjectName("lineEdit_whitelistpath")
        self.pushButton_whitelistsave = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_whitelistsave.setGeometry(QtCore.QRect(560, 380, 75, 23))
        self.pushButton_whitelistsave.setObjectName("pushButton_whitelistsave")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_par = QtWidgets.QWidget()
        self.tab_par.setObjectName("tab_par")
        self.textBrowser_help = QtWidgets.QTextBrowser(self.tab_par)
        self.textBrowser_help.setGeometry(QtCore.QRect(10, 10, 621, 391))
        self.textBrowser_help.setObjectName("textBrowser_help")
        self.tabWidget.addTab(self.tab_par, "")
        self.pushButton_help = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_help.setGeometry(QtCore.QRect(460, 22, 75, 23))
        self.pushButton_help.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_help.setObjectName("pushButton_help")
        self.pushButton_about = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_about.setGeometry(QtCore.QRect(550, 22, 75, 23))
        self.pushButton_about.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_about.setObjectName("pushButton_about")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_time = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_time.setEnabled(False)
        self.lineEdit_time.setGeometry(QtCore.QRect(460, 0, 165, 20))
        self.lineEdit_time.setObjectName("lineEdit_time")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 648, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MonkeyTest_Tool"))
        self.label_2.setText(_translate("MainWindow", "Device_1:"))
        self.label_3.setText(_translate("MainWindow", "Device_2:"))
        self.label_4.setText(_translate("MainWindow", "Device_3:"))
        self.label_5.setText(_translate("MainWindow", "Device_4:"))
        self.label_6.setText(_translate("MainWindow", "Device_5:"))
        self.label_7.setText(_translate("MainWindow", "Device_6:"))
        self.label_8.setText(_translate("MainWindow", "Device_7:"))
        self.label_9.setText(_translate("MainWindow", "Device_8:"))
        self.label_10.setText(_translate("MainWindow", "Device_9:"))
        self.label_11.setText(_translate("MainWindow", "Device_10:"))
        self.pushButton_getDevicesID.setText(_translate("MainWindow", "GET DEVICES ID"))
        self.pushButton_getDevicesID_2.setText(_translate("MainWindow", "SAVE "))
        self.pushButton_stop1.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop2.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop3.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop4.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop5.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop6.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop7.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop8.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop9.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop10.setText(_translate("MainWindow", "Stop Monkey"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_devices), _translate("MainWindow", "Devices"))
        self.checkBox_isCerStop_All.setText(_translate("MainWindow", "忽略发生证书或网络许可异常"))
        self.label_times_all.setText(_translate("MainWindow", "测 试 次 数："))
        self.label_dely_all.setText(_translate("MainWindow", "时 延："))
        self.checkBox_isRushStop_All.setText(_translate("MainWindow", "忽略程序崩溃"))
        self.checkBox_isAnrStop_All.setText(_translate("MainWindow", "忽略发生 ANR"))
        self.checkBox_isAppErrStop_All.setText(_translate("MainWindow", "忽略应用程序发生错误"))
        self.pushButton_start_All.setText(_translate("MainWindow", "开始 Monkey 测试"))
        self.checkBox.setText(_translate("MainWindow", "是否添加 Black List"))
        self.checkBox_kill_all.setText(_translate("MainWindow", "忽略发生任何错误异常"))
        self.checkBox_2.setText(_translate("MainWindow", "是否添加 White List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_all), _translate("MainWindow", "monkey测试"))
        self.label_seed.setText(_translate("MainWindow", "SEED："))
        self.label_flip.setText(_translate("MainWindow", "Flip："))
        self.label_touch.setText(_translate("MainWindow", "Touch："))
        self.label_trackball.setText(_translate("MainWindow", "TrackBall："))
        self.label_majornav.setText(_translate("MainWindow", "Majornav："))
        self.label_appswitch.setText(_translate("MainWindow", "AppSwitch："))
        self.label_motion.setText(_translate("MainWindow", "Motion："))
        self.label_nav.setText(_translate("MainWindow", "Nav："))
        self.label_syskeys.setText(_translate("MainWindow", "Syskeys："))
        self.label_anyevent.setText(_translate("MainWindow", "Anyevent："))
        self.pushButton_resetpar.setText(_translate("MainWindow", "重置参数"))
        self.pushButton_savepar.setText(_translate("MainWindow", "保存参数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "参数设置"))
        self.pushButton_addbacklist.setText(_translate("MainWindow", "+"))
        self.pushButton_rmbacklist.setText(_translate("MainWindow", "-"))
        self.pushButton_getPackNamebacklist.setText(_translate("MainWindow", "GET"))
        self.pushButton_saveBlacklist.setText(_translate("MainWindow", "SAVE"))
        self.label_balcklistpath.setText(_translate("MainWindow", "BlackListPath："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_black), _translate("MainWindow", "Black List"))
        self.pushButton_whitelistget.setText(_translate("MainWindow", "GET"))
        self.pushButton_whitelistadd.setText(_translate("MainWindow", "+"))
        self.pushButton_whitelistrm.setText(_translate("MainWindow", "-"))
        self.label_whitelistpath.setText(_translate("MainWindow", "White List Path："))
        self.pushButton_whitelistsave.setText(_translate("MainWindow", "SAVE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "White List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_par), _translate("MainWindow", "Description"))
        self.pushButton_help.setText(_translate("MainWindow", "Help"))
        self.pushButton_about.setText(_translate("MainWindow", "About"))
        self.label.setText(_translate("MainWindow", "Monkey Test Tool"))

