#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019/3/18 16:36
# @Author  : LiuXiangNan
# @Site    : 
# @File    : APNUI.py


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(707, 699)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, -20, 561, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_about = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_about.setGeometry(QtCore.QRect(600, 15, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_about.setFont(font)
        self.pushButton_about.setObjectName("pushButton_about")
        self.label_path = QtWidgets.QLabel(self.centralwidget)
        self.label_path.setGeometry(QtCore.QRect(40, 155, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_path.setFont(font)
        self.label_path.setObjectName("label_path")
        self.lineEdit_path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_path.setGeometry(QtCore.QRect(160, 160, 461, 30))
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.toolButton_path = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_path.setGeometry(QtCore.QRect(630, 160, 51, 30))
        self.toolButton_path.setObjectName("toolButton_path")
        self.pushButton_import = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_import.setGeometry(QtCore.QRect(20, 270, 661, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_import.setFont(font)
        self.pushButton_import.setObjectName("pushButton_import")
        self.label_sheet = QtWidgets.QLabel(self.centralwidget)
        self.label_sheet.setGeometry(QtCore.QRect(50, 215, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_sheet.setFont(font)
        self.label_sheet.setObjectName("label_sheet")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setEnabled(True)
        self.comboBox.setGeometry(QtCore.QRect(160, 210, 461, 30))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 350, 671, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(20, 390, 661, 261))
        self.listView.setObjectName("listView")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 60, 691, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.checkBox_xml = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_xml.setGeometry(QtCore.QRect(210, 110, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_xml.setFont(font)
        self.checkBox_xml.setObjectName("checkBox_xml")
        self.checkBox_excel = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_excel.setGeometry(QtCore.QRect(400, 110, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setItalic(False)
        self.checkBox_excel.setFont(font)
        self.checkBox_excel.setObjectName("checkBox_excel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 707, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FunctionMobileAPNImport"))
        self.label.setText(_translate("MainWindow", "APN 参数导入(试用版)"))
        self.pushButton_about.setText(_translate("MainWindow", "About"))
        self.label_path.setText(_translate("MainWindow", "导入文件路径:"))
        self.toolButton_path.setText(_translate("MainWindow", "..."))
        self.pushButton_import.setText(_translate("MainWindow", "导入数据至服务端"))
        self.label_sheet.setText(_translate("MainWindow", "Sheet 名："))
        self.checkBox_xml.setText(_translate("MainWindow", "XML文件"))
        self.checkBox_excel.setText(_translate("MainWindow", "EXCEL文件"))
        self.label_2.setText(_translate("MainWindow", "导入文件类型:"))

