# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_functionAPNTest.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 461)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 0, 611, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_about = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_about.setGeometry(QtCore.QRect(660, 30, 75, 23))
        self.pushButton_about.setObjectName("pushButton_about")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 70, 750, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_list = QtWidgets.QLabel(self.centralwidget)
        self.label_list.setGeometry(QtCore.QRect(40, 100, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_list.setFont(font)
        self.label_list.setObjectName("label_list")
        self.comboBox_list = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_list.setGeometry(QtCore.QRect(120, 100, 521, 30))
        self.comboBox_list.setObjectName("comboBox_list")
        self.pushButton_getlist = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_getlist.setGeometry(QtCore.QRect(660, 100, 75, 31))
        self.pushButton_getlist.setObjectName("pushButton_getlist")
        self.label_apn = QtWidgets.QLabel(self.centralwidget)
        self.label_apn.setGeometry(QtCore.QRect(40, 170, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_apn.setFont(font)
        self.label_apn.setObjectName("label_apn")
        self.lineEdit_apnpath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_apnpath.setGeometry(QtCore.QRect(120, 170, 521, 30))
        self.lineEdit_apnpath.setObjectName("lineEdit_apnpath")
        self.toolButton_apnselect = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_apnselect.setGeometry(QtCore.QRect(660, 170, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.toolButton_apnselect.setFont(font)
        self.toolButton_apnselect.setObjectName("toolButton_apnselect")
        self.pushButton_starttest = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_starttest.setGeometry(QtCore.QRect(20, 300, 731, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_starttest.setFont(font)
        self.pushButton_starttest.setObjectName("pushButton_starttest")
        self.label_apn_reportpath = QtWidgets.QLabel(self.centralwidget)
        self.label_apn_reportpath.setGeometry(QtCore.QRect(10, 240, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_apn_reportpath.setFont(font)
        self.label_apn_reportpath.setObjectName("label_apn_reportpath")
        self.lineEdit_apnpath_reportpath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_apnpath_reportpath.setGeometry(QtCore.QRect(120, 240, 521, 30))
        self.lineEdit_apnpath_reportpath.setObjectName("lineEdit_apnpath_reportpath")
        self.toolButton_apnselect_reportpath = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_apnselect_reportpath.setGeometry(QtCore.QRect(660, 240, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.toolButton_apnselect_reportpath.setFont(font)
        self.toolButton_apnselect_reportpath.setObjectName("toolButton_apnselect_reportpath")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 380, 741, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 772, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sagereal APN Test Tool"))
        self.label.setText(_translate("MainWindow", "Sagereal 功能机 APN 测试 Tool"))
        self.pushButton_about.setText(_translate("MainWindow", "About"))
        self.label_list.setText(_translate("MainWindow", "市场列表:"))
        self.pushButton_getlist.setText(_translate("MainWindow", "获取列表"))
        self.label_apn.setText(_translate("MainWindow", "APN 文件:"))
        self.toolButton_apnselect.setText(_translate("MainWindow", "..."))
        self.pushButton_starttest.setText(_translate("MainWindow", "START TEST"))
        self.label_apn_reportpath.setText(_translate("MainWindow", "Report Path:"))
        self.toolButton_apnselect_reportpath.setText(_translate("MainWindow", "..."))

