# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MonkeyTestUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 540)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 60, 801, 541))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_devices = QtWidgets.QWidget()
        self.tab_devices.setObjectName("tab_devices")
        self.label_2 = QtWidgets.QLabel(self.tab_devices)
        self.label_2.setGeometry(QtCore.QRect(40, 12, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_device1 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device1.setGeometry(QtCore.QRect(110, 17, 151, 20))
        self.lineEdit_device1.setObjectName("lineEdit_device1")
        self.checkBox_device1 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device1.setGeometry(QtCore.QRect(270, 20, 16, 16))
        self.checkBox_device1.setText("")
        self.checkBox_device1.setObjectName("checkBox_device1")
        self.label_3 = QtWidgets.QLabel(self.tab_devices)
        self.label_3.setGeometry(QtCore.QRect(40, 82, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.checkBox_device2 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device2.setGeometry(QtCore.QRect(270, 90, 16, 16))
        self.checkBox_device2.setText("")
        self.checkBox_device2.setObjectName("checkBox_device2")
        self.lineEdit_device2 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device2.setGeometry(QtCore.QRect(110, 87, 151, 20))
        self.lineEdit_device2.setObjectName("lineEdit_device2")
        self.lineEdit_device3 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device3.setGeometry(QtCore.QRect(110, 157, 151, 20))
        self.lineEdit_device3.setObjectName("lineEdit_device3")
        self.label_4 = QtWidgets.QLabel(self.tab_devices)
        self.label_4.setGeometry(QtCore.QRect(40, 152, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.checkBox_device3 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device3.setGeometry(QtCore.QRect(270, 160, 16, 16))
        self.checkBox_device3.setText("")
        self.checkBox_device3.setObjectName("checkBox_device3")
        self.lineEdit_device4 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device4.setGeometry(QtCore.QRect(110, 227, 151, 20))
        self.lineEdit_device4.setObjectName("lineEdit_device4")
        self.label_5 = QtWidgets.QLabel(self.tab_devices)
        self.label_5.setGeometry(QtCore.QRect(40, 222, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.checkBox_device4 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device4.setGeometry(QtCore.QRect(270, 230, 16, 16))
        self.checkBox_device4.setText("")
        self.checkBox_device4.setObjectName("checkBox_device4")
        self.lineEdit_device5 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device5.setGeometry(QtCore.QRect(110, 297, 151, 20))
        self.lineEdit_device5.setObjectName("lineEdit_device5")
        self.label_6 = QtWidgets.QLabel(self.tab_devices)
        self.label_6.setGeometry(QtCore.QRect(40, 292, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.checkBox_device5 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device5.setGeometry(QtCore.QRect(270, 300, 16, 16))
        self.checkBox_device5.setText("")
        self.checkBox_device5.setObjectName("checkBox_device5")
        self.lineEdit_device6 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device6.setGeometry(QtCore.QRect(420, 17, 151, 20))
        self.lineEdit_device6.setObjectName("lineEdit_device6")
        self.label_7 = QtWidgets.QLabel(self.tab_devices)
        self.label_7.setGeometry(QtCore.QRect(350, 12, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.checkBox_device6 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device6.setGeometry(QtCore.QRect(580, 20, 16, 16))
        self.checkBox_device6.setText("")
        self.checkBox_device6.setObjectName("checkBox_device6")
        self.lineEdit_device7 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device7.setGeometry(QtCore.QRect(420, 87, 151, 20))
        self.lineEdit_device7.setObjectName("lineEdit_device7")
        self.label_8 = QtWidgets.QLabel(self.tab_devices)
        self.label_8.setGeometry(QtCore.QRect(350, 82, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.checkBox_device7 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device7.setGeometry(QtCore.QRect(580, 90, 16, 16))
        self.checkBox_device7.setText("")
        self.checkBox_device7.setObjectName("checkBox_device7")
        self.lineEdit_device8 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device8.setGeometry(QtCore.QRect(420, 157, 151, 20))
        self.lineEdit_device8.setObjectName("lineEdit_device8")
        self.label_9 = QtWidgets.QLabel(self.tab_devices)
        self.label_9.setGeometry(QtCore.QRect(350, 152, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.checkBox_device8 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device8.setGeometry(QtCore.QRect(580, 160, 16, 16))
        self.checkBox_device8.setText("")
        self.checkBox_device8.setObjectName("checkBox_device8")
        self.lineEdit_device9 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device9.setGeometry(QtCore.QRect(420, 227, 151, 20))
        self.lineEdit_device9.setObjectName("lineEdit_device9")
        self.label_10 = QtWidgets.QLabel(self.tab_devices)
        self.label_10.setGeometry(QtCore.QRect(350, 222, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.checkBox_device9 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device9.setGeometry(QtCore.QRect(580, 230, 16, 16))
        self.checkBox_device9.setText("")
        self.checkBox_device9.setObjectName("checkBox_device9")
        self.lineEdit_device10 = QtWidgets.QLineEdit(self.tab_devices)
        self.lineEdit_device10.setGeometry(QtCore.QRect(420, 297, 151, 20))
        self.lineEdit_device10.setObjectName("lineEdit_device10")
        self.label_11 = QtWidgets.QLabel(self.tab_devices)
        self.label_11.setGeometry(QtCore.QRect(340, 292, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.checkBox_device10 = QtWidgets.QCheckBox(self.tab_devices)
        self.checkBox_device10.setGeometry(QtCore.QRect(580, 300, 16, 16))
        self.checkBox_device10.setText("")
        self.checkBox_device10.setObjectName("checkBox_device10")
        self.pushButton_getDevicesID = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_getDevicesID.setGeometry(QtCore.QRect(50, 370, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_getDevicesID.setFont(font)
        self.pushButton_getDevicesID.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_getDevicesID.setObjectName("pushButton_getDevicesID")
        self.pushButton_getDevicesID_2 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_getDevicesID_2.setGeometry(QtCore.QRect(350, 370, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_getDevicesID_2.setFont(font)
        self.pushButton_getDevicesID_2.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_getDevicesID_2.setObjectName("pushButton_getDevicesID_2")
        self.pushButton_stop1 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop1.setGeometry(QtCore.QRect(110, 50, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop1.setFont(font)
        self.pushButton_stop1.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop1.setObjectName("pushButton_stop1")
        self.pushButton_stop2 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop2.setGeometry(QtCore.QRect(110, 120, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop2.setFont(font)
        self.pushButton_stop2.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop2.setObjectName("pushButton_stop2")
        self.pushButton_stop3 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop3.setGeometry(QtCore.QRect(110, 190, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop3.setFont(font)
        self.pushButton_stop3.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop3.setObjectName("pushButton_stop3")
        self.pushButton_stop4 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop4.setGeometry(QtCore.QRect(110, 260, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop4.setFont(font)
        self.pushButton_stop4.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop4.setObjectName("pushButton_stop4")
        self.pushButton_stop5 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop5.setGeometry(QtCore.QRect(110, 330, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop5.setFont(font)
        self.pushButton_stop5.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop5.setObjectName("pushButton_stop5")
        self.pushButton_stop6 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop6.setGeometry(QtCore.QRect(420, 50, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop6.setFont(font)
        self.pushButton_stop6.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop6.setObjectName("pushButton_stop6")
        self.pushButton_stop7 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop7.setGeometry(QtCore.QRect(420, 120, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop7.setFont(font)
        self.pushButton_stop7.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop7.setObjectName("pushButton_stop7")
        self.pushButton_stop8 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop8.setGeometry(QtCore.QRect(420, 190, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop8.setFont(font)
        self.pushButton_stop8.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop8.setObjectName("pushButton_stop8")
        self.pushButton_stop9 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop9.setGeometry(QtCore.QRect(420, 260, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop9.setFont(font)
        self.pushButton_stop9.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop9.setObjectName("pushButton_stop9")
        self.pushButton_stop10 = QtWidgets.QPushButton(self.tab_devices)
        self.pushButton_stop10.setGeometry(QtCore.QRect(420, 330, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop10.setFont(font)
        self.pushButton_stop10.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_stop10.setObjectName("pushButton_stop10")
        self.tabWidget.addTab(self.tab_devices, "")
        self.tab_all = QtWidgets.QWidget()
        self.tab_all.setObjectName("tab_all")
        self.checkBox_isCerStop_All = QtWidgets.QCheckBox(self.tab_all)
        self.checkBox_isCerStop_All.setGeometry(QtCore.QRect(40, 280, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_isCerStop_All.setFont(font)
        self.checkBox_isCerStop_All.setObjectName("checkBox_isCerStop_All")
        self.lineEdit_time_all = QtWidgets.QLineEdit(self.tab_all)
        self.lineEdit_time_all.setGeometry(QtCore.QRect(140, 65, 181, 25))
        self.lineEdit_time_all.setObjectName("lineEdit_time_all")
        self.label_times_all = QtWidgets.QLabel(self.tab_all)
        self.label_times_all.setGeometry(QtCore.QRect(40, 65, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_times_all.setFont(font)
        self.label_times_all.setObjectName("label_times_all")
        self.lineEdit_dely_all = QtWidgets.QLineEdit(self.tab_all)
        self.lineEdit_dely_all.setGeometry(QtCore.QRect(410, 65, 161, 25))
        self.lineEdit_dely_all.setObjectName("lineEdit_dely_all")
        self.label_dely_all = QtWidgets.QLabel(self.tab_all)
        self.label_dely_all.setGeometry(QtCore.QRect(360, 65, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_dely_all.setFont(font)
        self.label_dely_all.setObjectName("label_dely_all")
        self.checkBox_isRushStop_All = QtWidgets.QCheckBox(self.tab_all)
        self.checkBox_isRushStop_All.setGeometry(QtCore.QRect(310, 190, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_isRushStop_All.setFont(font)
        self.checkBox_isRushStop_All.setObjectName("checkBox_isRushStop_All")
        self.checkBox_isAnrStop_All = QtWidgets.QCheckBox(self.tab_all)
        self.checkBox_isAnrStop_All.setGeometry(QtCore.QRect(40, 235, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_isAnrStop_All.setFont(font)
        self.checkBox_isAnrStop_All.setObjectName("checkBox_isAnrStop_All")
        self.checkBox_isAppErrStop_All = QtWidgets.QCheckBox(self.tab_all)
        self.checkBox_isAppErrStop_All.setGeometry(QtCore.QRect(310, 235, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_isAppErrStop_All.setFont(font)
        self.checkBox_isAppErrStop_All.setObjectName("checkBox_isAppErrStop_All")
        self.pushButton_start_All = QtWidgets.QPushButton(self.tab_all)
        self.pushButton_start_All.setGeometry(QtCore.QRect(40, 330, 541, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_start_All.setFont(font)
        self.pushButton_start_All.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_start_All.setObjectName("pushButton_start_All")
        self.label_android_all = QtWidgets.QLabel(self.tab_all)
        self.label_android_all.setGeometry(QtCore.QRect(40, 20, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_android_all.setFont(font)
        self.label_android_all.setObjectName("label_android_all")
        self.comboBox_android_All = QtWidgets.QComboBox(self.tab_all)
        self.comboBox_android_All.setEnabled(True)
        self.comboBox_android_All.setGeometry(QtCore.QRect(140, 20, 431, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_android_All.setFont(font)
        self.comboBox_android_All.setObjectName("comboBox_android_All")
        self.comboBox_android_All.addItem("")
        self.comboBox_android_All.addItem("")
        self.comboBox_android_All.addItem("")
        self.comboBox_android_All.addItem("")
        self.checkBox = QtWidgets.QCheckBox(self.tab_all)
        self.checkBox.setGeometry(QtCore.QRect(40, 190, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.label_log_all = QtWidgets.QLabel(self.tab_all)
        self.label_log_all.setGeometry(QtCore.QRect(40, 140, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_log_all.setFont(font)
        self.label_log_all.setObjectName("label_log_all")
        self.lineEdit_log_all = QtWidgets.QLineEdit(self.tab_all)
        self.lineEdit_log_all.setGeometry(QtCore.QRect(140, 140, 381, 25))
        self.lineEdit_log_all.setObjectName("lineEdit_log_all")
        self.toolButton_log_all = QtWidgets.QToolButton(self.tab_all)
        self.toolButton_log_all.setGeometry(QtCore.QRect(530, 140, 37, 28))
        self.toolButton_log_all.setStyleSheet("background-color:rgb(211, 211, 230))")
        self.toolButton_log_all.setObjectName("toolButton_log_all")
        self.checkBox_kill_all = QtWidgets.QCheckBox(self.tab_all)
        self.checkBox_kill_all.setGeometry(QtCore.QRect(310, 280, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_kill_all.setFont(font)
        self.checkBox_kill_all.setObjectName("checkBox_kill_all")
        self.label_log_all_2 = QtWidgets.QLabel(self.tab_all)
        self.label_log_all_2.setGeometry(QtCore.QRect(40, 105, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_log_all_2.setFont(font)
        self.label_log_all_2.setObjectName("label_log_all_2")
        self.comboBox_log_level_all = QtWidgets.QComboBox(self.tab_all)
        self.comboBox_log_level_all.setGeometry(QtCore.QRect(140, 105, 181, 22))
        self.comboBox_log_level_all.setObjectName("comboBox_log_level_all")
        self.comboBox_log_level_all.addItem("")
        self.comboBox_log_level_all.addItem("")
        self.comboBox_log_level_all.addItem("")
        self.comboBox_log_level_all.addItem("")
        self.checkBox_isoutputLog_All = QtWidgets.QCheckBox(self.tab_all)
        self.checkBox_isoutputLog_All.setGeometry(QtCore.QRect(360, 110, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_isoutputLog_All.setFont(font)
        self.checkBox_isoutputLog_All.setObjectName("checkBox_isoutputLog_All")
        self.tabWidget.addTab(self.tab_all, "")
        self.tab_single = QtWidgets.QWidget()
        self.tab_single.setObjectName("tab_single")
        self.label_appName_Single = QtWidgets.QLabel(self.tab_single)
        self.label_appName_Single.setGeometry(QtCore.QRect(40, 65, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_appName_Single.setFont(font)
        self.label_appName_Single.setObjectName("label_appName_Single")
        self.label_times_Single = QtWidgets.QLabel(self.tab_single)
        self.label_times_Single.setGeometry(QtCore.QRect(40, 110, 111, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_times_Single.setFont(font)
        self.label_times_Single.setObjectName("label_times_Single")
        self.lineEdit_times_Single = QtWidgets.QLineEdit(self.tab_single)
        self.lineEdit_times_Single.setGeometry(QtCore.QRect(170, 110, 141, 25))
        self.lineEdit_times_Single.setObjectName("lineEdit_times_Single")
        self.checkBox_isAppErrStop_Single = QtWidgets.QCheckBox(self.tab_single)
        self.checkBox_isAppErrStop_Single.setGeometry(QtCore.QRect(40, 270, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_isAppErrStop_Single.setFont(font)
        self.checkBox_isAppErrStop_Single.setObjectName("checkBox_isAppErrStop_Single")
        self.label_dely_Single = QtWidgets.QLabel(self.tab_single)
        self.label_dely_Single.setGeometry(QtCore.QRect(370, 110, 61, 30))
        self.label_dely_Single.setObjectName("label_dely_Single")
        self.checkBox_isAnrStop_Single = QtWidgets.QCheckBox(self.tab_single)
        self.checkBox_isAnrStop_Single.setGeometry(QtCore.QRect(310, 270, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_isAnrStop_Single.setFont(font)
        self.checkBox_isAnrStop_Single.setObjectName("checkBox_isAnrStop_Single")
        self.checkBox_isCerStop_Single = QtWidgets.QCheckBox(self.tab_single)
        self.checkBox_isCerStop_Single.setGeometry(QtCore.QRect(40, 300, 531, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_isCerStop_Single.setFont(font)
        self.checkBox_isCerStop_Single.setObjectName("checkBox_isCerStop_Single")
        self.checkBox_isRushStop_Single = QtWidgets.QCheckBox(self.tab_single)
        self.checkBox_isRushStop_Single.setGeometry(QtCore.QRect(40, 230, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_isRushStop_Single.setFont(font)
        self.checkBox_isRushStop_Single.setObjectName("checkBox_isRushStop_Single")
        self.lineEdit_dely_Single = QtWidgets.QLineEdit(self.tab_single)
        self.lineEdit_dely_Single.setGeometry(QtCore.QRect(442, 110, 125, 25))
        self.lineEdit_dely_Single.setObjectName("lineEdit_dely_Single")
        self.pushButton_StartTest_Single = QtWidgets.QPushButton(self.tab_single)
        self.pushButton_StartTest_Single.setGeometry(QtCore.QRect(40, 340, 540, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_StartTest_Single.setFont(font)
        self.pushButton_StartTest_Single.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_StartTest_Single.setObjectName("pushButton_StartTest_Single")
        self.label_android_single = QtWidgets.QLabel(self.tab_single)
        self.label_android_single.setGeometry(QtCore.QRect(40, 20, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_android_single.setFont(font)
        self.label_android_single.setObjectName("label_android_single")
        self.comboBox_android_Single = QtWidgets.QComboBox(self.tab_single)
        self.comboBox_android_Single.setEnabled(True)
        self.comboBox_android_Single.setGeometry(QtCore.QRect(170, 20, 397, 25))
        self.comboBox_android_Single.setEditable(False)
        self.comboBox_android_Single.setObjectName("comboBox_android_Single")
        self.comboBox_android_Single.addItem("")
        self.comboBox_android_Single.addItem("")
        self.comboBox_android_Single.addItem("")
        self.comboBox_android_Single.addItem("")
        self.comboBox_testName_Single = QtWidgets.QComboBox(self.tab_single)
        self.comboBox_testName_Single.setEnabled(True)
        self.comboBox_testName_Single.setGeometry(QtCore.QRect(170, 65, 397, 25))
        self.comboBox_testName_Single.setEditable(True)
        self.comboBox_testName_Single.setObjectName("comboBox_testName_Single")
        self.label_log_single = QtWidgets.QLabel(self.tab_single)
        self.label_log_single.setGeometry(QtCore.QRect(40, 185, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_log_single.setFont(font)
        self.label_log_single.setObjectName("label_log_single")
        self.lineEdit_log_Single = QtWidgets.QLineEdit(self.tab_single)
        self.lineEdit_log_Single.setGeometry(QtCore.QRect(170, 190, 351, 25))
        self.lineEdit_log_Single.setObjectName("lineEdit_log_Single")
        self.toolButton_log_single = QtWidgets.QToolButton(self.tab_single)
        self.toolButton_log_single.setGeometry(QtCore.QRect(530, 190, 37, 25))
        self.toolButton_log_single.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.toolButton_log_single.setObjectName("toolButton_log_single")
        self.checkBox_kill_single = QtWidgets.QCheckBox(self.tab_single)
        self.checkBox_kill_single.setGeometry(QtCore.QRect(310, 230, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_kill_single.setFont(font)
        self.checkBox_kill_single.setObjectName("checkBox_kill_single")
        self.checkBox_isOutputLog_Single = QtWidgets.QCheckBox(self.tab_single)
        self.checkBox_isOutputLog_Single.setGeometry(QtCore.QRect(370, 155, 191, 16))
        self.checkBox_isOutputLog_Single.setObjectName("checkBox_isOutputLog_Single")
        self.comboBox_logleve_Single = QtWidgets.QComboBox(self.tab_single)
        self.comboBox_logleve_Single.setGeometry(QtCore.QRect(170, 150, 141, 22))
        self.comboBox_logleve_Single.setObjectName("comboBox_logleve_Single")
        self.comboBox_logleve_Single.addItem("")
        self.comboBox_logleve_Single.addItem("")
        self.comboBox_logleve_Single.addItem("")
        self.comboBox_logleve_Single.addItem("")
        self.label_log_single_2 = QtWidgets.QLabel(self.tab_single)
        self.label_log_single_2.setGeometry(QtCore.QRect(40, 155, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_log_single_2.setFont(font)
        self.label_log_single_2.setObjectName("label_log_single_2")
        self.tabWidget.addTab(self.tab_single, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.spinBox_seed = QtWidgets.QSpinBox(self.tab)
        self.spinBox_seed.setGeometry(QtCore.QRect(120, 40, 111, 30))
        self.spinBox_seed.setObjectName("spinBox_seed")
        self.label_seed = QtWidgets.QLabel(self.tab)
        self.label_seed.setGeometry(QtCore.QRect(60, 40, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_seed.setFont(font)
        self.label_seed.setObjectName("label_seed")
        self.spinBox_flip = QtWidgets.QSpinBox(self.tab)
        self.spinBox_flip.setGeometry(QtCore.QRect(430, 40, 111, 30))
        self.spinBox_flip.setObjectName("spinBox_flip")
        self.label_flip = QtWidgets.QLabel(self.tab)
        self.label_flip.setGeometry(QtCore.QRect(370, 40, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_flip.setFont(font)
        self.label_flip.setObjectName("label_flip")
        self.spinBox_touch = QtWidgets.QSpinBox(self.tab)
        self.spinBox_touch.setGeometry(QtCore.QRect(120, 100, 111, 30))
        self.spinBox_touch.setObjectName("spinBox_touch")
        self.label_touch = QtWidgets.QLabel(self.tab)
        self.label_touch.setGeometry(QtCore.QRect(50, 100, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_touch.setFont(font)
        self.label_touch.setObjectName("label_touch")
        self.spinBox_trackball = QtWidgets.QSpinBox(self.tab)
        self.spinBox_trackball.setGeometry(QtCore.QRect(120, 160, 111, 30))
        self.spinBox_trackball.setObjectName("spinBox_trackball")
        self.label_trackball = QtWidgets.QLabel(self.tab)
        self.label_trackball.setGeometry(QtCore.QRect(22, 160, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_trackball.setFont(font)
        self.label_trackball.setObjectName("label_trackball")
        self.spinBox_majornav = QtWidgets.QSpinBox(self.tab)
        self.spinBox_majornav.setGeometry(QtCore.QRect(120, 220, 111, 30))
        self.spinBox_majornav.setObjectName("spinBox_majornav")
        self.label_majornav = QtWidgets.QLabel(self.tab)
        self.label_majornav.setGeometry(QtCore.QRect(30, 220, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_majornav.setFont(font)
        self.label_majornav.setObjectName("label_majornav")
        self.spinBox_appswitch = QtWidgets.QSpinBox(self.tab)
        self.spinBox_appswitch.setGeometry(QtCore.QRect(120, 290, 111, 30))
        self.spinBox_appswitch.setObjectName("spinBox_appswitch")
        self.label_appswitch = QtWidgets.QLabel(self.tab)
        self.label_appswitch.setGeometry(QtCore.QRect(20, 290, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_appswitch.setFont(font)
        self.label_appswitch.setObjectName("label_appswitch")
        self.spinBox_motion = QtWidgets.QSpinBox(self.tab)
        self.spinBox_motion.setGeometry(QtCore.QRect(430, 100, 111, 30))
        self.spinBox_motion.setObjectName("spinBox_motion")
        self.label_motion = QtWidgets.QLabel(self.tab)
        self.label_motion.setGeometry(QtCore.QRect(355, 100, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_motion.setFont(font)
        self.label_motion.setObjectName("label_motion")
        self.spinBox_nav = QtWidgets.QSpinBox(self.tab)
        self.spinBox_nav.setGeometry(QtCore.QRect(430, 160, 111, 30))
        self.spinBox_nav.setObjectName("spinBox_nav")
        self.label_nav = QtWidgets.QLabel(self.tab)
        self.label_nav.setGeometry(QtCore.QRect(375, 160, 31, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_nav.setFont(font)
        self.label_nav.setObjectName("label_nav")
        self.spinBox_syskeys = QtWidgets.QSpinBox(self.tab)
        self.spinBox_syskeys.setGeometry(QtCore.QRect(430, 220, 111, 30))
        self.spinBox_syskeys.setObjectName("spinBox_syskeys")
        self.label_syskeys = QtWidgets.QLabel(self.tab)
        self.label_syskeys.setGeometry(QtCore.QRect(345, 220, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_syskeys.setFont(font)
        self.label_syskeys.setObjectName("label_syskeys")
        self.spinBox_anyevent = QtWidgets.QSpinBox(self.tab)
        self.spinBox_anyevent.setGeometry(QtCore.QRect(430, 290, 111, 30))
        self.spinBox_anyevent.setObjectName("spinBox_anyevent")
        self.label_anyevent = QtWidgets.QLabel(self.tab)
        self.label_anyevent.setGeometry(QtCore.QRect(335, 290, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_anyevent.setFont(font)
        self.label_anyevent.setObjectName("label_anyevent")
        self.pushButton_resetpar = QtWidgets.QPushButton(self.tab)
        self.pushButton_resetpar.setGeometry(QtCore.QRect(50, 360, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_resetpar.setFont(font)
        self.pushButton_resetpar.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_resetpar.setObjectName("pushButton_resetpar")
        self.pushButton_savepar = QtWidgets.QPushButton(self.tab)
        self.pushButton_savepar.setGeometry(QtCore.QRect(340, 360, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_savepar.setFont(font)
        self.pushButton_savepar.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_savepar.setObjectName("pushButton_savepar")
        self.tabWidget.addTab(self.tab, "")
        self.tab_black = QtWidgets.QWidget()
        self.tab_black.setObjectName("tab_black")
        self.pushButton_add = QtWidgets.QPushButton(self.tab_black)
        self.pushButton_add.setGeometry(QtCore.QRect(280, 170, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_rm = QtWidgets.QPushButton(self.tab_black)
        self.pushButton_rm.setGeometry(QtCore.QRect(280, 260, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_rm.setFont(font)
        self.pushButton_rm.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_rm.setObjectName("pushButton_rm")
        self.listView_app = QtWidgets.QListView(self.tab_black)
        self.listView_app.setGeometry(QtCore.QRect(10, 10, 256, 361))
        self.listView_app.setObjectName("listView_app")
        self.listView_black = QtWidgets.QListView(self.tab_black)
        self.listView_black.setGeometry(QtCore.QRect(340, 10, 256, 361))
        self.listView_black.setObjectName("listView_black")
        self.pushButton_getPackName = QtWidgets.QPushButton(self.tab_black)
        self.pushButton_getPackName.setGeometry(QtCore.QRect(280, 80, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_getPackName.setFont(font)
        self.pushButton_getPackName.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_getPackName.setObjectName("pushButton_getPackName")
        self.pushButton_saveBlacklist = QtWidgets.QPushButton(self.tab_black)
        self.pushButton_saveBlacklist.setGeometry(QtCore.QRect(550, 380, 45, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_saveBlacklist.setFont(font)
        self.pushButton_saveBlacklist.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_saveBlacklist.setObjectName("pushButton_saveBlacklist")
        self.label_balcklistpath = QtWidgets.QLabel(self.tab_black)
        self.label_balcklistpath.setGeometry(QtCore.QRect(10, 380, 121, 30))
        self.label_balcklistpath.setObjectName("label_balcklistpath")
        self.lineEdit_black_list_path = QtWidgets.QLineEdit(self.tab_black)
        self.lineEdit_black_list_path.setGeometry(QtCore.QRect(137, 380, 401, 30))
        self.lineEdit_black_list_path.setObjectName("lineEdit_black_list_path")
        self.tabWidget.addTab(self.tab_black, "")
        self.tab_par = QtWidgets.QWidget()
        self.tab_par.setObjectName("tab_par")
        self.textBrowser_help = QtWidgets.QTextBrowser(self.tab_par)
        self.textBrowser_help.setGeometry(QtCore.QRect(10, 10, 591, 391))
        self.textBrowser_help.setObjectName("textBrowser_help")
        self.tabWidget.addTab(self.tab_par, "")
        self.pushButton_help = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_help.setGeometry(QtCore.QRect(390, 20, 75, 23))
        self.pushButton_help.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_help.setObjectName("pushButton_help")
        self.pushButton_about = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_about.setGeometry(QtCore.QRect(490, 20, 75, 23))
        self.pushButton_about.setStyleSheet("background-color:rgb(211, 211, 230)")
        self.pushButton_about.setObjectName("pushButton_about")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        self.comboBox_android_Single.setCurrentIndex(0)
        self.comboBox_testName_Single.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MonkeyTest_Tool"))
        self.label_2.setText(_translate("MainWindow", "Device_1:"))
        self.label_3.setText(_translate("MainWindow", "Device_2:"))
        self.label_4.setText(_translate("MainWindow", "Device_3:"))
        self.label_5.setText(_translate("MainWindow", "Device_4:"))
        self.label_6.setText(_translate("MainWindow", "Device_5:"))
        self.label_7.setText(_translate("MainWindow", "Device_6:"))
        self.label_8.setText(_translate("MainWindow", "Device_7:"))
        self.label_9.setText(_translate("MainWindow", "Device_8:"))
        self.label_10.setText(_translate("MainWindow", "Device_9:"))
        self.label_11.setText(_translate("MainWindow", "Device_10:"))
        self.pushButton_getDevicesID.setText(_translate("MainWindow", "GET DEVICES ID"))
        self.pushButton_getDevicesID_2.setText(_translate("MainWindow", "SAVE "))
        self.pushButton_stop1.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop2.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop3.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop4.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop5.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop6.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop7.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop8.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop9.setText(_translate("MainWindow", "Stop Monkey"))
        self.pushButton_stop10.setText(_translate("MainWindow", "Stop Monkey"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_devices), _translate("MainWindow", "Devices"))
        self.checkBox_isCerStop_All.setText(_translate("MainWindow", "忽略发生证书或网络许可异常"))
        self.label_times_all.setText(_translate("MainWindow", "测 试 次 数："))
        self.label_dely_all.setText(_translate("MainWindow", "时 延："))
        self.checkBox_isRushStop_All.setText(_translate("MainWindow", "忽略程序崩溃"))
        self.checkBox_isAnrStop_All.setText(_translate("MainWindow", "忽略发生 ANR"))
        self.checkBox_isAppErrStop_All.setText(_translate("MainWindow", "忽略应用程序发生错误"))
        self.pushButton_start_All.setText(_translate("MainWindow", "开始 Monkey 测试"))
        self.label_android_all.setText(_translate("MainWindow", "Android 平台："))
        self.comboBox_android_All.setItemText(0, _translate("MainWindow", "Android M"))
        self.comboBox_android_All.setItemText(1, _translate("MainWindow", "Android N"))
        self.comboBox_android_All.setItemText(2, _translate("MainWindow", "Android GO"))
        self.comboBox_android_All.setItemText(3, _translate("MainWindow", "Android P"))
        self.checkBox.setText(_translate("MainWindow", "是否添加屏蔽应用"))
        self.label_log_all.setText(_translate("MainWindow", "Log路径名称："))
        self.toolButton_log_all.setText(_translate("MainWindow", "..."))
        self.checkBox_kill_all.setText(_translate("MainWindow", "忽略发生任何错误异常"))
        self.label_log_all_2.setText(_translate("MainWindow", "输出Log等级："))
        self.comboBox_log_level_all.setItemText(0, _translate("MainWindow", "Level_0"))
        self.comboBox_log_level_all.setItemText(1, _translate("MainWindow", "Level_1"))
        self.comboBox_log_level_all.setItemText(2, _translate("MainWindow", "Level_2"))
        self.comboBox_log_level_all.setItemText(3, _translate("MainWindow", "Level_3"))
        self.checkBox_isoutputLog_All.setText(_translate("MainWindow", "是否输出Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_all), _translate("MainWindow", "全 APP 测试"))
        self.label_appName_Single.setText(_translate("MainWindow", "测试 APP 包名："))
        self.label_times_Single.setText(_translate("MainWindow", "测 试 次 数："))
        self.checkBox_isAppErrStop_Single.setText(_translate("MainWindow", "忽略应用程序发生错误"))
        self.label_dely_Single.setText(_translate("MainWindow", "时  延："))
        self.checkBox_isAnrStop_Single.setText(_translate("MainWindow", "忽略发生 ANR "))
        self.checkBox_isCerStop_Single.setText(_translate("MainWindow", "忽略应用程序发生许可错误（如证书许可，网络许可等）"))
        self.checkBox_isRushStop_Single.setText(_translate("MainWindow", "忽略程序崩溃"))
        self.pushButton_StartTest_Single.setText(_translate("MainWindow", "开始 monkey 测试"))
        self.label_android_single.setText(_translate("MainWindow", "Android 平台："))
        self.comboBox_android_Single.setItemText(0, _translate("MainWindow", "Android M"))
        self.comboBox_android_Single.setItemText(1, _translate("MainWindow", "Android N"))
        self.comboBox_android_Single.setItemText(2, _translate("MainWindow", "Android GO"))
        self.comboBox_android_Single.setItemText(3, _translate("MainWindow", "Android P"))
        self.label_log_single.setText(_translate("MainWindow", "Log路径名称："))
        self.toolButton_log_single.setText(_translate("MainWindow", "..."))
        self.checkBox_kill_single.setText(_translate("MainWindow", "忽略发生任何错误"))
        self.checkBox_isOutputLog_Single.setText(_translate("MainWindow", "是否输出Log"))
        self.comboBox_logleve_Single.setItemText(0, _translate("MainWindow", "Level_0"))
        self.comboBox_logleve_Single.setItemText(1, _translate("MainWindow", "Level_1"))
        self.comboBox_logleve_Single.setItemText(2, _translate("MainWindow", "Level_2"))
        self.comboBox_logleve_Single.setItemText(3, _translate("MainWindow", "Level_3"))
        self.label_log_single_2.setText(_translate("MainWindow", "输出Log等级："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_single), _translate("MainWindow", "单包测试"))
        self.label_seed.setText(_translate("MainWindow", "SEED："))
        self.label_flip.setText(_translate("MainWindow", "Flip："))
        self.label_touch.setText(_translate("MainWindow", "Touch："))
        self.label_trackball.setText(_translate("MainWindow", "TrackBall："))
        self.label_majornav.setText(_translate("MainWindow", "Majornav："))
        self.label_appswitch.setText(_translate("MainWindow", "AppSwitch："))
        self.label_motion.setText(_translate("MainWindow", "Motion："))
        self.label_nav.setText(_translate("MainWindow", "Nav："))
        self.label_syskeys.setText(_translate("MainWindow", "Syskeys："))
        self.label_anyevent.setText(_translate("MainWindow", "Anyevent："))
        self.pushButton_resetpar.setText(_translate("MainWindow", "重置参数"))
        self.pushButton_savepar.setText(_translate("MainWindow", "保存参数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "参数设置"))
        self.pushButton_add.setText(_translate("MainWindow", "+"))
        self.pushButton_rm.setText(_translate("MainWindow", "-"))
        self.pushButton_getPackName.setText(_translate("MainWindow", "GET"))
        self.pushButton_saveBlacklist.setText(_translate("MainWindow", "SAVE"))
        self.label_balcklistpath.setText(_translate("MainWindow", "BlackListPath："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_black), _translate("MainWindow", "Black List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_par), _translate("MainWindow", "Description"))
        self.pushButton_help.setText(_translate("MainWindow", "Help"))
        self.pushButton_about.setText(_translate("MainWindow", "About"))
        self.label.setText(_translate("MainWindow", "Monkey Test Tool"))

