#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019/3/18 16:42
# @Author  : LiuXiangNan
# @Site    :
# @File    : UI_functionAPNTest.py

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 498)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 0, 611, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_about = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_about.setGeometry(QtCore.QRect(660, 30, 75, 23))
        self.pushButton_about.setObjectName("pushButton_about")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 65, 771, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 771, 371))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_country = QtWidgets.QLabel(self.tab)
        self.label_country.setGeometry(QtCore.QRect(370, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_country.setFont(font)
        self.label_country.setObjectName("label_country")
        self.label_list_2 = QtWidgets.QLabel(self.tab)
        self.label_list_2.setGeometry(QtCore.QRect(40, 80, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_list_2.setFont(font)
        self.label_list_2.setObjectName("label_list_2")
        self.pushButton_getlist_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_getlist_2.setGeometry(QtCore.QRect(660, 80, 75, 31))
        self.pushButton_getlist_2.setObjectName("pushButton_getlist_2")
        self.comboBox_list_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_list_2.setGeometry(QtCore.QRect(120, 80, 521, 30))
        self.comboBox_list_2.setObjectName("comboBox_list_2")
        self.toolButton_apnselect_2 = QtWidgets.QToolButton(self.tab)
        self.toolButton_apnselect_2.setGeometry(QtCore.QRect(660, 130, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.toolButton_apnselect_2.setFont(font)
        self.toolButton_apnselect_2.setObjectName("toolButton_apnselect_2")
        self.lineEdit_apnpath_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_apnpath_2.setGeometry(QtCore.QRect(120, 130, 521, 30))
        self.lineEdit_apnpath_2.setObjectName("lineEdit_apnpath_2")
        self.label_apn_singler = QtWidgets.QLabel(self.tab)
        self.label_apn_singler.setGeometry(QtCore.QRect(40, 130, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_apn_singler.setFont(font)
        self.label_apn_singler.setObjectName("label_apn_singler")
        self.label_apn_reportpath_2 = QtWidgets.QLabel(self.tab)
        self.label_apn_reportpath_2.setGeometry(QtCore.QRect(10, 190, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_apn_reportpath_2.setFont(font)
        self.label_apn_reportpath_2.setObjectName("label_apn_reportpath_2")
        self.lineEdit_apnpath_reportpath_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_apnpath_reportpath_2.setGeometry(QtCore.QRect(120, 190, 521, 30))
        self.lineEdit_apnpath_reportpath_2.setObjectName("lineEdit_apnpath_reportpath_2")
        self.toolButton_apnselect_reportpath_2 = QtWidgets.QToolButton(self.tab)
        self.toolButton_apnselect_reportpath_2.setGeometry(QtCore.QRect(660, 190, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.toolButton_apnselect_reportpath_2.setFont(font)
        self.toolButton_apnselect_reportpath_2.setObjectName("toolButton_apnselect_reportpath_2")
        self.pushButton_starttest_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_starttest_2.setGeometry(QtCore.QRect(10, 240, 731, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_starttest_2.setFont(font)
        self.pushButton_starttest_2.setObjectName("pushButton_starttest_2")
        self.progressBar_2 = QtWidgets.QProgressBar(self.tab)
        self.progressBar_2.setGeometry(QtCore.QRect(10, 320, 741, 23))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.label_market = QtWidgets.QLabel(self.tab)
        self.label_market.setGeometry(QtCore.QRect(20, 20, 41, 30))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_market.setFont(font)
        self.label_market.setObjectName("label_market")
        self.comboBox_market = QtWidgets.QComboBox(self.tab)
        self.comboBox_market.setGeometry(QtCore.QRect(80, 20, 241, 30))
        self.comboBox_market.setObjectName("comboBox_market")
        self.comboBox_market.addItem("")
        self.comboBox_market.addItem("")
        self.comboBox_market.addItem("")
        self.comboBox_market.addItem("")
        self.comboBox_country2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_country2.setGeometry(QtCore.QRect(440, 20, 291, 30))
        self.comboBox_country2.setObjectName("comboBox_country2")
        self.tabWidget.addTab(self.tab, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.toolButton_apnselect = QtWidgets.QToolButton(self.tab1)
        self.toolButton_apnselect.setGeometry(QtCore.QRect(660, 90, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.toolButton_apnselect.setFont(font)
        self.toolButton_apnselect.setObjectName("toolButton_apnselect")
        self.lineEdit_apnpath_reportpath = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_apnpath_reportpath.setGeometry(QtCore.QRect(120, 160, 521, 30))
        self.lineEdit_apnpath_reportpath.setObjectName("lineEdit_apnpath_reportpath")
        self.comboBox_list = QtWidgets.QComboBox(self.tab1)
        self.comboBox_list.setGeometry(QtCore.QRect(120, 20, 521, 30))
        self.comboBox_list.setObjectName("comboBox_list")
        self.label_list = QtWidgets.QLabel(self.tab1)
        self.label_list.setGeometry(QtCore.QRect(40, 20, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_list.setFont(font)
        self.label_list.setObjectName("label_list")
        self.pushButton_getlist = QtWidgets.QPushButton(self.tab1)
        self.pushButton_getlist.setGeometry(QtCore.QRect(660, 20, 75, 31))
        self.pushButton_getlist.setObjectName("pushButton_getlist")
        self.toolButton_apnselect_reportpath = QtWidgets.QToolButton(self.tab1)
        self.toolButton_apnselect_reportpath.setGeometry(QtCore.QRect(660, 160, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.toolButton_apnselect_reportpath.setFont(font)
        self.toolButton_apnselect_reportpath.setObjectName("toolButton_apnselect_reportpath")
        self.lineEdit_apnpath = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_apnpath.setGeometry(QtCore.QRect(120, 90, 521, 30))
        self.lineEdit_apnpath.setObjectName("lineEdit_apnpath")
        self.pushButton_starttest = QtWidgets.QPushButton(self.tab1)
        self.pushButton_starttest.setGeometry(QtCore.QRect(20, 220, 731, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_starttest.setFont(font)
        self.pushButton_starttest.setObjectName("pushButton_starttest")
        self.label_apn_reportpath = QtWidgets.QLabel(self.tab1)
        self.label_apn_reportpath.setGeometry(QtCore.QRect(10, 160, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_apn_reportpath.setFont(font)
        self.label_apn_reportpath.setObjectName("label_apn_reportpath")
        self.label_apn = QtWidgets.QLabel(self.tab1)
        self.label_apn.setGeometry(QtCore.QRect(40, 90, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_apn.setFont(font)
        self.label_apn.setObjectName("label_apn")
        self.progressBar = QtWidgets.QProgressBar(self.tab1)
        self.progressBar.setGeometry(QtCore.QRect(20, 300, 741, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.tab1, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "APN Test Tool"))
        self.label.setText(_translate("MainWindow", APN测试Tool(试用)"))
        self.pushButton_about.setText(_translate("MainWindow", "About"))
        self.label_country.setText(_translate("MainWindow", "国家码:"))
        self.label_list_2.setText(_translate("MainWindow", "市场名:"))
        self.pushButton_getlist_2.setText(_translate("MainWindow", "获取列表"))
        self.toolButton_apnselect_2.setText(_translate("MainWindow", "..."))
        self.label_apn_singler.setText(_translate("MainWindow", "APN 文件:"))
        self.label_apn_reportpath_2.setText(_translate("MainWindow", "Report Path:"))
        self.toolButton_apnselect_reportpath_2.setText(_translate("MainWindow", "..."))
        self.pushButton_starttest_2.setText(_translate("MainWindow", "START TEST"))
        self.label_market.setText(_translate("MainWindow", "市场："))
        self.comboBox_market.setItemText(0, _translate("MainWindow", "非洲-中东-欧洲市场"))
        self.comboBox_market.setItemText(1, _translate("MainWindow", "东南亚市场"))
        self.comboBox_market.setItemText(2, _translate("MainWindow", "美洲市场"))
        self.comboBox_market.setItemText(3, _translate("MainWindow", "印度市场"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "按国家码测试"))
        self.toolButton_apnselect.setText(_translate("MainWindow", "..."))
        self.label_list.setText(_translate("MainWindow", "市场列表:"))
        self.pushButton_getlist.setText(_translate("MainWindow", "获取列表"))
        self.toolButton_apnselect_reportpath.setText(_translate("MainWindow", "..."))
        self.pushButton_starttest.setText(_translate("MainWindow", "START TEST"))
        self.label_apn_reportpath.setText(_translate("MainWindow", "Report Path:"))
        self.label_apn.setText(_translate("MainWindow", "APN 文件:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "按市场测试"))

